AWSTemplateFormatVersion: 2010-09-09
Description: 'Cross-Region AWS Config Organizational Conformance Pack deployment'

Parameters:

  pArtifactBucketName:
    Description: 'Artifact storage S3 bucket name'
    Type: String
    AllowedPattern: ^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: 'S3 Bucket name value must contain only alphanumeric characters and hyphens'

  pStackSetAdminRoleName:
    Description: 'The administration role name for CloudFormation StackSets with self-managed permission deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetAdministrationRole'

  pStackExecutionRoleName:
    Description: 'The execution role name for CloudFormation StackSets with self-managed permission deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetExecutionRole'

  pEnabledRegions:
    Description: 'Comma separated list of enabled AWS regions (e.g. us-east-1,us-west-2)'
    Type: String
    AllowedPattern: '^$|^([a-z0-9-]{1,64})$|^(([a-z0-9-]{1,64},)*[a-z0-9-]{1,64})$'
    ConstraintDescription: 'Only lowercase letters, numbers, and hyphens are allowed (e.g. us-east-1,us-west-2)'

  pConfigConformsPackDeliveryBucketName:
    Description: 'AWS Config Organization Conformance Pack Delivery Bucket Name'
    Type: String
    AllowedPattern: ^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: 'S3 Bucket name value must contain only alphanumeric characters and hyphens'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Resources:

  rOrganizationConformancePackStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'aws-config-org-conforms-packs'
      Description: 'Deploys AWS Config Organizational Conformance Packs to Multiple Regions'
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pStackSetAdminRoleName}'
      ExecutionRoleName: !Ref pStackExecutionRoleName
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: 'PARALLEL'
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
          Regions: !Split [ ',', !Ref pEnabledRegions ]
      TemplateURL: !Sub 'https://${pArtifactBucketName}.s3.amazonaws.com/aws-config-org-conforms-packs.yaml'
      Parameters:
        - ParameterKey: pArtifactBucketName
          ParameterValue: !Ref pArtifactBucketName
        - ParameterKey: pConfigConformsPackDeliveryBucketName
          ParameterValue: !Ref pConfigConformsPackDeliveryBucketName
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
