AWSTemplateFormatVersion: 2010-09-09
Description: 'SNS Topic for AWS Config'

Parameters:

  pOrgID:
    Description: 'AWS Organization ID (e.g., o-abc1234567)'
    Type: String
    AllowedPattern: '^o-[a-zA-Z0-9]{10}$'
    ConstraintDescription: 'Must be a valid AWS Organization ID (e.g., o-abc1234567)'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Resources:

  rConfigSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'aws-config-org-stream-${AWS::Region}'
      DisplayName: 'Stream of AWS Config configuration changes and notifications from all org accounts in this region'
      #KmsMasterKeyId: 'alias/aws/sns'
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

  rConfigSNSTopicPolicy:
    Type: AWS::SNS::TopicInlinePolicy
    Properties:
      TopicArn: !Ref rConfigSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSConfigSNSPolicy
            Effect: Allow
            Principal:
              Service: 'config.amazonaws.com'
            Action:
              - 'sns:Publish'
            Resource: !Ref rConfigSNSTopic
            Condition:
              StringEquals:
                aws:SourceOrgID: !Ref pOrgID

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
