AWSTemplateFormatVersion: 2010-09-09
Description: 'Organization wide security event bus and alerts'

Parameters:

  pProjectName:
    Description: 'Project Name (value used in the "project" tag)'
    Type: String
    Default: 'org-sec-alerts'
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Project name value must contain only alphanumeric characters, hyphens, and underscores'

  pOrgID:
    Description: 'AWS Organization ID (e.g., o-abc1234567)'
    Type: String
    AllowedPattern: '^o-[a-zA-Z0-9]{10}$'
    ConstraintDescription: 'Must be a valid AWS Organization ID (e.g., o-abc1234567)'

  pDeployEmailAlerts:
    Description: 'Deploy e-mail alerts? (When enabled, deploys an SNS topic subscribed to the specified email)'
    Type: String
    Default: 'no'
    AllowedValues:
         - 'yes'
         - 'no'

  pCriticalAlertEmail:
    Description: 'Organization-wide critical security alerts email address (Required if e-mail alerts are enabled)'
    Type: String
    AllowedPattern: ".{0}|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
    ConstraintDescription: 'Must be a valid email address'

Conditions:

  cDeployEmailAlerts: !Equals [ !Ref pDeployEmailAlerts, 'yes']
  cDeployAlerts: !Equals [ !Ref pDeployEmailAlerts, 'yes']

Resources:

  rOrgSecEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: 'org-sec-event-bus'
      Tags:
        - Key: 'project'
          Value: !Ref pProjectName

  rOrgSecEventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref rOrgSecEventBus
      StatementId: 'AllowOrgMemberAccountsToPutEvents'
      Statement:
        Effect: 'Allow'
        Principal: '*'
        Action: 'events:PutEvents'
        Resource: !GetAtt rOrgSecEventBus.Arn
        Condition:
          StringEquals:
            'aws:PrincipalOrgID': !Ref pOrgID

  rCriticalOrgSecEmailAlertsSNSTopic:
    Type: AWS::SNS::Topic
    Condition: cDeployEmailAlerts
    Properties:
      TopicName: 'org-sec-alerts-crit-email'
      # DisplayName is used as "from" name in the email
      DisplayName: 'Critical Security Alerts'
      Tags:
        - Key: 'project'
          Value: !Ref pProjectName

  rCriticalOrgSecEmailAlertsSNSTopicPolicy:
    Type: AWS::SNS::TopicInlinePolicy
    Condition: cDeployEmailAlerts
    Properties:
      TopicArn: !Ref rCriticalOrgSecEmailAlertsSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref rCriticalOrgSecEmailAlertsSNSTopic
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-signin-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-iam-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-sts-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-account-rule'

  rCriticalOrgSecEmailAlertsSNSTopicSub:
    Type: AWS::SNS::Subscription
    Condition: cDeployEmailAlerts
    Properties:
      Endpoint: !Ref pCriticalAlertEmail
      Protocol: email
      TopicArn: !Ref rCriticalOrgSecEmailAlertsSNSTopic

  rOrgSecAlertsDLQQueue:
    Type: AWS::SQS::Queue
    Condition: cDeployAlerts
    Properties:
      QueueName: 'org-sec-alerts-dlq'
      MessageRetentionPeriod: 604800
      SqsManagedSseEnabled: true
      Tags:
        - Key: 'project'
          Value: !Ref pProjectName

  rOrgSecAlertsDLQQueuePolicy:
    Type: AWS::SQS::QueueInlinePolicy
    Condition: cDeployAlerts
    Properties:
      Queue: !Ref rOrgSecAlertsDLQQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt rOrgSecAlertsDLQQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-signin-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-iam-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-root-sts-rule'
                  - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/org-sec-event-bus/org-sec-alerts-account-rule'

  rOrgSecAlertsRootSigninRule:
    Type: AWS::Events::Rule
    Condition: cDeployAlerts
    Properties:
      Name: 'org-sec-alerts-root-signin-rule'
      Description: 'Listens for root user events from the "signin" event source'
      EventBusName: !GetAtt rOrgSecEventBus.Arn
      State: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
      EventPattern:
        source:
          - 'aws.signin'
        detail-type:
          - 'AWS Console Sign In via CloudTrail'
        detail:
          userIdentity:
            $or:
              - type:
                  - 'Root'
              - sessionContext:
                  sessionIssuer:
                    type:
                      - 'Root'
          eventName:
            - 'ConsoleLogin'
            - 'GetSigninToken'
            - 'PasswordRecoveryRequested'
            - 'PasswordRecoveryCompleted'
            - 'EmailUpdated'
            - 'PasswordUpdated'
      Targets:
        - Id: 'CriticalOrgSecAlertSNSTopic'
          Arn: !Ref rCriticalOrgSecEmailAlertsSNSTopic
          DeadLetterConfig:
            Arn: !GetAtt rOrgSecAlertsDLQQueue.Arn
          InputTransformer:
            InputPathsMap:
              LoginTo: $.detail.additionalEventData.LoginTo
              MFAUsed: $.detail.additionalEventData.MFAUsed
              MobileVersion: $.detail.additionalEventData.MobileVersion
              accountId: $.detail.userIdentity.accountId
              arn: $.detail.userIdentity.arn
              awsRegion: $.detail.awsRegion
              eventID: $.detail.eventID
              eventName: $.detail.eventName
              eventTime: $.detail.eventTime
              principalId: $.detail.userIdentity.principalId
              sourceIPAddress: $.detail.sourceIPAddress
              userAgent: $.detail.userAgent
              userIdentityType: $.detail.userIdentity.type
              response: $.detail.responseElements[*]
              accessKeyId: $.detail.userIdentity.accessKeyId
              eventSource: $.detail.eventSource

            InputTemplate: |
              "----- ALERT | USER: <userIdentityType> | EVENT: signin:<eventName> | RESPONSE: <response> -----"

              "Account Id: <accountId>"
              "ARN: <arn>"
              "Principal Id: <principalId>"
              "Access Key Id: <accessKeyId>"
              "Event Time: <eventTime>"
              "Region: <awsRegion>"
              "IP Address: <sourceIPAddress>"
              "User Agent: <userAgent>"
              "MFA Used: <MFAUsed>"
              "Mobile Version: <MobileVersion>"
              "Event Source: <eventSource>"
              "CloudTrail Event ID: <eventID>"
              "URL: <LoginTo>"

  rOrgSecAlertsRootIAMRule:
    Type: AWS::Events::Rule
    Condition: cDeployAlerts
    Properties:
      Name: 'org-sec-alerts-root-iam-rule'
      Description: 'Listens for root user events from the "iam" event source'
      EventBusName: !GetAtt rOrgSecEventBus.Arn
      State: ENABLED
      EventPattern:
        source:
          - 'aws.iam'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          userIdentity:
            type:
              - 'Root'
          eventName:
            - 'CreateAccessKey'
            - 'UpdateAccessKey'
            - 'DeleteAccessKey'
            - 'UploadCloudFrontPublicKey'
            - 'UpdateCloudFrontPublicKey'
            - 'DeleteCloudFrontPublicKey'
            - 'UploadSigningCertificate'
            - 'UpdateSigningCertificate'
            - 'DeleteSigningCertificate'
            - 'CreateVirtualMFADevice'
            - 'DeleteVirtualMFADevice'
            - 'DeactivateMFADevice'
            - 'EnableMFADevice'
            - 'ResyncMFADevice'
            - 'ChangePassword'
            - 'UpdateAccountEmailAddress'
      Targets:
        - Id: 'CriticalOrgSecAlertSNSTopic'
          Arn: !Ref rCriticalOrgSecEmailAlertsSNSTopic
          DeadLetterConfig:
            Arn: !GetAtt rOrgSecAlertsDLQQueue.Arn
          InputTransformer:
            InputPathsMap:
              accountId: $.detail.userIdentity.accountId
              arn: $.detail.userIdentity.arn
              awsRegion: $.detail.awsRegion
              eventID: $.detail.eventID
              eventName: $.detail.eventName
              eventTime: $.detail.eventTime
              principalId: $.detail.userIdentity.principalId
              sourceIPAddress: $.detail.sourceIPAddress
              userAgent: $.detail.userAgent
              userIdentityType: $.detail.userIdentity.type
              accessKeyId: $.detail.userIdentity.accessKeyId
              eventSource: $.detail.eventSource
            InputTemplate: |
              "----- ALERT | USER: <userIdentityType> | EVENT: iam:<eventName> -----"

              "Account Id: <accountId>"
              "ARN: <arn>"
              "Principal Id: <principalId>"
              "Access Key Id: <accessKeyId>"
              "Event Time: <eventTime>"
              "Region: <awsRegion>"
              "IP Address: <sourceIPAddress>"
              "User Agent: <userAgent>"
              "Event Source: <eventSource>"
              "CloudTrail Event ID: <eventID>"

  rOrgSecAlertsRootSTSRule:
    Type: AWS::Events::Rule
    Condition: cDeployAlerts
    Properties:
      Name: 'org-sec-alerts-root-sts-rule'
      Description: 'Listens for root user events from the "sts" event source'
      EventBusName: !GetAtt rOrgSecEventBus.Arn
      State: ENABLED
      EventPattern:
        source:
          - 'aws.sts'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          userIdentity:
            type:
              - 'Root'
          eventName:
            - 'GetFederationToken'
            - 'GetSessionToken'
      Targets:
        - Id: 'CriticalOrgSecAlertSNSTopic'
          Arn: !Ref rCriticalOrgSecEmailAlertsSNSTopic
          DeadLetterConfig:
            Arn: !GetAtt rOrgSecAlertsDLQQueue.Arn
          InputTransformer:
            InputPathsMap:
              accountId: $.detail.userIdentity.accountId
              arn: $.detail.userIdentity.arn
              awsRegion: $.detail.awsRegion
              eventID: $.detail.eventID
              eventName: $.detail.eventName
              eventTime: $.detail.eventTime
              principalId: $.detail.userIdentity.principalId
              sourceIPAddress: $.detail.sourceIPAddress
              userAgent: $.detail.userAgent
              userIdentityType: $.detail.userIdentity.type
              accessKeyId: $.detail.userIdentity.accessKeyId
              eventSource: $.detail.eventSource
            InputTemplate: |
              "----- ALERT | USER: <userIdentityType> | EVENT: sts:<eventName> -----"

              "Account Id: <accountId>"
              "ARN: <arn>"
              "Principal Id: <principalId>"
              "Access Key Id: <accessKeyId>"
              "Event Time: <eventTime>"
              "Region: <awsRegion>"
              "IP Address: <sourceIPAddress>"
              "User Agent: <userAgent>"
              "Event Source: <eventSource>"
              "CloudTrail Event ID: <eventID>"

  rOrgSecAlertsAccountRule:
    Type: AWS::Events::Rule
    Condition: cDeployAlerts
    Properties:
      Name: 'org-sec-alerts-account-rule'
      Description: 'Listens for events from the "account" event source'
      EventBusName: !GetAtt rOrgSecEventBus.Arn
      State: ENABLED
      EventPattern:
        source:
          - 'aws.account'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'PutContactInformation'
      Targets:
        - Id: 'CriticalOrgSecAlertSNSTopic'
          Arn: !Ref rCriticalOrgSecEmailAlertsSNSTopic
          DeadLetterConfig:
            Arn: !GetAtt rOrgSecAlertsDLQQueue.Arn
          InputTransformer:
            InputPathsMap:
              accountId: $.detail.userIdentity.accountId
              arn: $.detail.userIdentity.arn
              awsRegion: $.detail.awsRegion
              eventID: $.detail.eventID
              eventName: $.detail.eventName
              eventTime: $.detail.eventTime
              principalId: $.detail.userIdentity.principalId
              sourceIPAddress: $.detail.sourceIPAddress
              userAgent: $.detail.userAgent
              userIdentityType: $.detail.userIdentity.type
              accessKeyId: $.detail.userIdentity.accessKeyId
              eventSource: $.detail.eventSource
            InputTemplate: |
              "----- ALERT | USER: <userIdentityType> | EVENT: account:<eventName> -----"

              "Account Id: <accountId>"
              "ARN: <arn>"
              "Principal Id: <principalId>"
              "Access Key Id: <accessKeyId>"
              "Event Time: <eventTime>"
              "Region: <awsRegion>"
              "IP Address: <sourceIPAddress>"
              "User Agent: <userAgent>"
              "Event Source: <eventSource>"
              "CloudTrail Event ID: <eventID>"

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.2'
