AWSTemplateFormatVersion: 2010-09-09
Description: 'Organization wide AWS IAM Access Analyzer deployment'

Parameters:

  pArtifactBucketName:
    Description: 'Artifact storage S3 bucket name'
    Type: String
    AllowedPattern: ^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: 'S3 Bucket name value must contain only alphanumeric characters and hyphens'

  pDeployTargetOrgUnitId:
    Description: 'The organization root ID or organizational unit (OU) IDs to which stacks deploy.'
    Type: String
    AllowedPattern: '^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$'

  pStackSetAdminRoleName:
    Description: 'The administration role name for CloudFormation StackSets with self-managed permission deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetAdministrationRole'

  pStackExecutionRoleName:
    Description: 'The execution role name for CloudFormation StackSets with self-managed permission deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetExecutionRole'

  pEnabledRegions:
    Description: 'Comma separated list of enabled AWS regions (e.g. us-east-1,us-west-2)'
    Type: String
    AllowedPattern: '^$|^([a-z0-9-]{1,64})$|^(([a-z0-9-]{1,64},)*[a-z0-9-]{1,64})$'
    ConstraintDescription: 'Only lowercase letters, numbers, and hyphens are allowed (e.g. us-east-1,us-west-2)'

  pManagementAccountId:
    Description: 'Organization Management Account ID'
    Type: String
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: 'Must be 12 digits'

  pSecurityToolingAccountId:
    Description: 'Security Tooling Account ID'
    Type: String
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: 'Must be 12 digits'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Resources:

  # deploy external access AWS IAM Access Analyzer (account trust) in every provided region of the organization management account
  rAccessAnalyzerExternalAccountMgmtAccountStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'iam-access-analyzer-external-access-account-mgmt'
      Description: 'Deploys external access AWS IAM Access Analyzer (account trust) in the org management account'
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pStackSetAdminRoleName}'
      ExecutionRoleName: !Ref pStackExecutionRoleName
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: 'PARALLEL'
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref pManagementAccountId
          Regions: !Split [ ',', !Ref pEnabledRegions ]
      TemplateURL: !Sub 'https://${pArtifactBucketName}.s3.amazonaws.com/iam-access-analyzer-external-access-account.yaml'
      Parameters:
        - ParameterKey: pManagementAccountId
          ParameterValue: !Ref pManagementAccountId
        - ParameterKey: pWorkloadIdTag
          ParameterValue: !Ref pWorkloadIdTag
        - ParameterKey: pEnvironmentIdTag
          ParameterValue: !Ref pEnvironmentIdTag
        - ParameterKey: pOwnerNameTag
          ParameterValue: !Ref pOwnerNameTag
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

  # deploy external access AWS IAM Access Analyzer (account trust) in every provided region of every organization member account
  rAccessAnalyzerExternalAccountStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'iam-access-analyzer-external-access-account'
      Description: 'Deploys external access AWS IAM Access Analyzer (account trust) in every org account'
      PermissionModel: SERVICE_MANAGED
      CallAs: DELEGATED_ADMIN
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: 'PARALLEL'
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref pDeployTargetOrgUnitId
          Regions: !Split [ ',', !Ref pEnabledRegions ]
      TemplateURL: !Sub 'https://${pArtifactBucketName}.s3.amazonaws.com/iam-access-analyzer-external-access-account.yaml'
      Parameters:
        - ParameterKey: pManagementAccountId
          ParameterValue: !Ref pManagementAccountId
        - ParameterKey: pWorkloadIdTag
          ParameterValue: !Ref pWorkloadIdTag
        - ParameterKey: pEnvironmentIdTag
          ParameterValue: !Ref pEnvironmentIdTag
        - ParameterKey: pOwnerNameTag
          ParameterValue: !Ref pOwnerNameTag
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

  # deploy external access AWS IAM Access Analyzer (organization trust) in every provided region of the security tooling account
  rAccessAnalyzerExternalOrgStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'iam-access-analyzer-external-access-org'
      Description: 'Deploys external access AWS IAM Access Analyzer (organization trust) in the security tooling account'
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pStackSetAdminRoleName}'
      ExecutionRoleName: !Ref pStackExecutionRoleName
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: 'PARALLEL'
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref pSecurityToolingAccountId
          Regions: !Split [ ',', !Ref pEnabledRegions ]
      TemplateURL: !Sub 'https://${pArtifactBucketName}.s3.amazonaws.com/iam-access-analyzer-external-access-org.yaml'
      Parameters:
        - ParameterKey: pWorkloadIdTag
          ParameterValue: !Ref pWorkloadIdTag
        - ParameterKey: pEnvironmentIdTag
          ParameterValue: !Ref pEnvironmentIdTag
        - ParameterKey: pOwnerNameTag
          ParameterValue: !Ref pOwnerNameTag
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
