AWSTemplateFormatVersion: 2010-09-09
Description: 'SCP: Prevent S3 Bucket Tampering'

Parameters:

  pPolicyName:
    Description: 'Policy Name'
    Type: String
    Default: 'PreventS3BucketTampering'

  pS3BucketArn:
    Description: 'Amazon S3 Bucket ARN. (Example: arn:aws:s3:::bucket-name)'
    Type: String

  pTargetIds:
    Type: String

Resources:

  rPolicy:
    Type: AWS::Organizations::Policy
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Ref pPolicyName
      Description: 'Prevent S3 Bucket Tampering'
      Content:
        Version: '2012-10-17'
        Statement:
          - Sid: PreventS3BucketTampering
            Effect: Deny
            Action:
              - 's3:DeleteBucket'
              - 's3:PutEncryptionConfiguration'
              - 's3:PutLifecycleConfiguration'
              - 's3:PutIntelligentTieringConfiguration'
              - 's3:PutBucketOwnershipControls'
              - 's3:PutBucketPolicy'
              - 's3:DeleteBucketPolicy'
              - 's3:PutReplicationConfiguration'
              - 's3:PutBucketTagging'
              - 's3:PutBucketWebsite'
              - 's3:DeleteBucketWebsite'
              - 's3:PutBucketCORS'
              - 's3:PutBucketPublicAccessBlock'
              - 's3:PutBucketAcl'
              - 's3:PutBucketLogging'
              - 's3:PutBucketNotification'
              - 's3:PutBucketVersioning'
              - 's3:PutBucketObjectLockConfiguration'
            Resource:
              - !Sub '${pS3BucketArn}*'
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
          - Sid: PreventS3ObjectTampering
            Effect: Deny
            Action:
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
            Resource:
              - !Sub '${pS3BucketArn}/*'
      TargetIds:
        - !Ref pTargetIds

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.1'
