AWSTemplateFormatVersion: 2010-09-09
Description: 'SCP: Prevent CloudWatch Logs Log Group Tampering'

Parameters:

  pPolicyName:
    Description: 'Policy Name'
    Type: String
    Default: 'PreventCloudWatchLogGroupTampering'

  pCloudWatchLogsLogGroupArns:
    Description: 'Comma separated list of Amazon CloudWatch Logs Log Group ARN(s). (Example: arn:aws:logs:us-east-1:123456789012:log-group:group-name:*)'
    Type: String

  pTargetIds:
    Type: String

Resources:

  rPolicy:
    Type: AWS::Organizations::Policy
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Ref pPolicyName
      Description: 'Prevent CloudWatch Logs Log Group Tampering'
      Content:
        Version: '2012-10-17'
        Statement:
          - Sid: PreventCloudWatchLogGroupTampering
            Effect: Deny
            Action:
              - 'logs:DeleteLogGroup'
              - 'logs:DeleteLogStream'
              - 'logs:AssociateKmsKey'
              - 'logs:DisassociateKmsKey'
              - 'logs:PutRetentionPolicy'
              - 'logs:DeleteRetentionPolicy'
            Resource:
              !Split [ ',', !Ref pCloudWatchLogsLogGroupArns ]
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
          - Sid: PreventCloudWatchLogGroupTagTampering
            Effect: Deny
            Action:
              - 'logs:TagResource'
              - 'logs:UntagResource'
            Resource:
              # remove the trailing (:*) from the ARN(s)
              !Split [ ',', !Join [ '', !Split [ ':*', !Ref pCloudWatchLogsLogGroupArns ]]]
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
      TargetIds:
        - !Ref pTargetIds

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.2'
