AWSTemplateFormatVersion: 2010-09-09
Description: 'SCP: Prevent KMS Key Tampering'

Parameters:

  pPolicyName:
    Description: 'Policy Name'
    Type: String
    Default: 'PreventKMSKeyTampering'

  pKMSKeyArns:
    Description: 'AWS KMS Key ARN(s)'
    Type: CommaDelimitedList

  pKMSKeyAliasArns:
    Description: 'AWS KMS Key Alias ARN(s)'
    Type: CommaDelimitedList

  pTargetIds:
    Type: String

Resources:

  rPolicy:
    Type: AWS::Organizations::Policy
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Ref pPolicyName
      Description: 'Prevent KMS Key Tampering'
      Content:
        Version: '2012-10-17'
        Statement:
          - Sid: PreventKMSKeyTampering
            Effect: Deny
            Action:
              - 'kms:ScheduleKeyDeletion'
              - 'kms:DisableKey'
              - 'kms:DisableKeyRotation'
              - 'kms:EnableKeyRotation'
              - 'kms:PutKeyPolicy'
              - 'kms:UpdateKeyDescription'
              - 'kms:TagResource'
              - 'kms:UntagResource'
            Resource:
              !Ref pKMSKeyArns
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
          - Sid: PreventKMSAliasTampering
            Effect: Deny
            Action:
              - 'kms:DeleteAlias'
              - 'kms:UpdateAlias'
            Resource:
              !Ref pKMSKeyAliasArns
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
      TargetIds:
        - !Ref pTargetIds

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.2'
