AWSTemplateFormatVersion: 2010-09-09
Description: 'SCP: Prevent AWS Security Hub Tampering'

Parameters:

  pPolicyName:
    Description: 'Policy Name'
    Type: String
    Default: 'PreventSecurityHubTampering'

  pTargetIds:
    Type: String

Resources:

  rPolicy:
    Type: AWS::Organizations::Policy
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Ref pPolicyName
      Description: 'Prevent AWS Security Hub Tampering'
      Content:
        Version: '2012-10-17'
        Statement:

          - Sid: PreventSecurityHubTampering
            Effect: Deny
            Action:
              - 'securityhub:CreateMembers'
              - 'securityhub:InviteMembers'
              - 'securityhub:AcceptAdministratorInvitation'
              - 'securityhub:AcceptInvitation'
              - 'securityhub:DeclineInvitations'
              - 'securityhub:DeleteInvitations'
              - 'securityhub:DisassociateMembers'
              - 'securityhub:DeleteMembers'
              - 'securityhub:DisassociateFromAdministratorAccount'
              - 'securityhub:DisassociateFromMasterAccount'
              - 'securityhub:DisableSecurityHub'
              - 'securityhub:DisableImportFindingsForProduct'
              - 'securityhub:DeleteFindingAggregator'
              - 'securityhub:UpdateFindingAggregator'
              - 'securityhub:BatchDisableStandards'
              - 'securityhub:BatchUpdateStandardsControlAssociations'
              - 'securityhub:UpdateStandardsControl'
              - 'securityhub:UpdateSecurityControl'
              - 'securityhub:CreateAutomationRule'
              - 'securityhub:BatchDeleteAutomationRules'
              - 'securityhub:BatchUpdateAutomationRules'
              - 'securityhub:DeleteConfigurationPolicy'
              - 'securityhub:UpdateConfigurationPolicy'
              - 'securityhub:StartConfigurationPolicyAssociation'
              - 'securityhub:StartConfigurationPolicyDisassociation'
              - 'securityhub:TagResource'
              - 'securityhub:UntagResource'
            Resource:
              - '*'
            Condition:
              ArnNotLike:
                'aws:PrincipalArn':
                  - 'arn:aws:iam::*:role/[AUTOMATION_ROLE]'
      TargetIds:
        - !Ref pTargetIds

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
