AWSTemplateFormatVersion: 2010-09-09
Description: 'Execution Role for CloudFormation StackSets with Self-Managed Permission Deployments'

Parameters:

  pAdminRoleArn:
    Description: 'ARN of the Admin Role for CloudFormation StackSets with Self-Managed Permission Deployments'
    Type: String

  pExecutionRoleName:
    Description: 'Name of the Execution Role for CloudFormation StackSets with Self-Managed Permission Deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetExecutionRole'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    Default: 'deployment'
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Resources:

  rExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref pExecutionRoleName
      Description: 'Execution Role for CloudFormation StackSets with Self-Managed Permission Deployments'
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref pAdminRoleArn
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess'
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
