AWSTemplateFormatVersion: 2010-09-09
Description: 'Deploys IAM Roles for CloudFormation StackSets with Self-Managed Permission Deployments'

Parameters:

  pArtifactBucketURL:
    Description: 'CloudFormation template storage bucket URL (i.e. https://bucket-name.s3.amazonaws.com)'
    Type: 'String'

  pDeployTargetOrgUnitId:
    Description: 'The organization root ID or organizational unit (OU) IDs to which stacks deploy.'
    Type: String
    AllowedPattern: '^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$'

  pOrgID:
    Description: 'AWS Organization ID (e.g., o-abc1234567)'
    Type: String
    AllowedPattern: '^o-[a-zA-Z0-9]{10}$'
    ConstraintDescription: 'Must be a valid AWS Organization ID (e.g., o-abc1234567)'

  pAdminRoleName:
    Description: 'Name of the Admin Role for CloudFormation StackSets with Self-Managed Permission Deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetAdministrationRole'

  pExecutionRoleName:
    Description: 'Name of the Execution Role for CloudFormation StackSets with Self-Managed Permission Deployments'
    Type: String
    Default: 'AWSCloudFormationStackSetExecutionRole'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    Default: 'deployment'
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Resources:

  rAdminRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${pArtifactBucketURL}/cfn-stackset-roles-admin-role.yaml'
      Parameters:
        pOrgID: !Ref pOrgID
        pAdminRoleName: !Ref pAdminRoleName
        pExecutionRoleName: !Ref pExecutionRoleName
        pWorkloadIdTag: !Ref pWorkloadIdTag
        pEnvironmentIdTag: !Ref pEnvironmentIdTag
        pOwnerNameTag: !Ref pOwnerNameTag
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

  rExecutionRoleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: 'cfn-stackset-execution-role'
      Description: 'Organizational StackSet to deploy execution role for CloudFormation StackSets with Self-Managed permission deployments'
      PermissionModel: SERVICE_MANAGED
      CallAs: DELEGATED_ADMIN
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_NAMED_IAM
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: 'PARALLEL'
      Parameters:
        - ParameterKey: pAdminRoleArn
          ParameterValue: !GetAtt [rAdminRoleStack, Outputs.oAdminRoleArn]
        - ParameterKey: pExecutionRoleName
          ParameterValue: !Ref pExecutionRoleName
        - ParameterKey: pWorkloadIdTag
          ParameterValue: !Ref pWorkloadIdTag
        - ParameterKey: pEnvironmentIdTag
          ParameterValue: !Ref pEnvironmentIdTag
        - ParameterKey: pOwnerNameTag
          ParameterValue: !Ref pOwnerNameTag
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref pDeployTargetOrgUnitId
          Regions:
            - !Ref AWS::Region
      TemplateURL: !Sub '${pArtifactBucketURL}/cfn-stackset-roles-execution-role.yaml'
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.0'
