AWSTemplateFormatVersion: 2010-09-09
Description: 'Security alert forwarding to the central event bus'

Parameters:

  pOrgSecEventBus:
    Description: 'Organization wide security alert event bus ARN'
    Type: String

  pHomeRegion:
    Description: 'Name of the home region (region where global resources will be deployed)'
    Type: String
    AllowedPattern: '^[a-z0-9-]{1,64}$'
    ConstraintDescription: 'Must be AWS Region (e.g. us-east-1)'

  pWorkloadIdTag:
    Description: 'Workload Id (value used in the "workload-id" tag)'
    Type: String
    Default: 'org-sec-alerts'
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Workload Id value must contain only alphanumeric characters, hyphens, and underscores'

  pEnvironmentIdTag:
    Description: 'Environment Id (value used in the "environment-id" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Environment Id value must contain only alphanumeric characters, hyphens, and underscores'

  pOwnerNameTag:
    Description: 'Owner Name (value used in the "owner" tag)'
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-_]+'
    ConstraintDescription: 'Owner name value must contain only alphanumeric characters, hyphens, and underscores'

Conditions:

  cDeployGlobalResources: !Equals [ !Ref 'AWS::Region', !Ref pHomeRegion ]

Resources:

  rOrgSecAlertsEventFwdRuleRole:
    Condition: cDeployGlobalResources
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'org-sec-alerts-event-fwd-rule-role'
      Description: 'Execution role for "org-sec-alerts" event forwarding rules'
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:${AWS::Partition}:events:*:${AWS::AccountId}:rule/org-sec-alerts-*'
      Policies:
        - PolicyName: put-events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource:
                  - !Ref pOrgSecEventBus
      Tags:
        - Key: 'workload-id'
          Value: !Ref pWorkloadIdTag
        - Key: 'environment-id'
          Value: !Ref pEnvironmentIdTag
        - Key: 'owner'
          Value: !Ref pOwnerNameTag

  rOrgSecAlertsRootSigninFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-root-signin-fwd-rule'
      Description: 'Forwards root user events from the "signin" event source to the central event bus'
      EventBusName: default
      State: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
      EventPattern:
        source:
          - 'aws.signin'
        detail-type:
          - 'AWS Console Sign In via CloudTrail'
        detail:
          userIdentity:
            $or:
              - type:
                  - 'Root'
              - sessionContext:
                  sessionIssuer:
                    type:
                      - 'Root'
          eventName:
            - 'ConsoleLogin'
            - 'GetSigninToken'
            - 'PasswordRecoveryRequested'
            - 'PasswordRecoveryCompleted'
            - 'EmailUpdated'
            - 'PasswordUpdated'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsRootIAMFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-root-iam-fwd-rule'
      Description: 'Forwards root user events from the "iam" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.iam'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          userIdentity:
            type:
              - 'Root'
          eventName:
            - 'CreateAccessKey'
            - 'UpdateAccessKey'
            - 'DeleteAccessKey'
            - 'UploadCloudFrontPublicKey'
            - 'UpdateCloudFrontPublicKey'
            - 'DeleteCloudFrontPublicKey'
            - 'UploadSigningCertificate'
            - 'UpdateSigningCertificate'
            - 'DeleteSigningCertificate'
            - 'CreateVirtualMFADevice'
            - 'DeleteVirtualMFADevice'
            - 'DeactivateMFADevice'
            - 'EnableMFADevice'
            - 'ResyncMFADevice'
            - 'ChangePassword'
            - 'UpdateAccountEmailAddress'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsRootSTSFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-root-sts-fwd-rule'
      Description: 'Forwards root user events from the "sts" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.sts'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          userIdentity:
            type:
              - 'Root'
          eventName:
            - 'GetFederationToken'
            - 'GetSessionToken'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsAccountFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-account-fwd-rule'
      Description: 'Forwards events from the "account" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.account'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'PutContactInformation'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsKMSFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-kms-fwd-rule'
      Description: 'Forwards events from the "kms" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.kms'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'ScheduleKeyDeletion'
            - 'DisableKey'
            - 'EnableKey'
            - 'DisableKeyRotation'
            - 'EnableKeyRotation'
            - 'PutKeyPolicy'
            - 'UpdateKeyDescription'
            - 'TagResource'
            - 'UntagResource'
            - 'DeleteAlias'
            - 'UpdateAlias'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsCloudTrailFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-cloudtrail-fwd-rule'
      Description: 'Forwards events from the "cloudtrail" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.cloudtrail'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'AddTags'
            - 'RemoveTags'
            - 'DeleteTrail'
            - 'UpdateTrail'
            - 'StopLogging'
            - 'StartLogging'
            - 'PutEventSelectors'
            - 'PutInsightSelectors'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsS3FwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-s3-fwd-rule'
      Description: 'Forwards events from the "s3" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.s3'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'DeleteBucket'
            - 'PutBucketEncryption'
            - 'DeleteBucketEncryption'
            - 'PutBucketLifecycle'
            - 'PutBucketIntelligentTieringConfiguration'
            - 'DeleteBucketIntelligentTieringConfiguration'
            - 'DeleteBucketLifecycle'
            - 'PutBucketOwnershipControls'
            - 'DeleteBucketOwnershipControls'
            - 'PutBucketPolicy'
            - 'DeleteBucketPolicy'
            - 'PutBucketReplication'
            - 'DeleteBucketReplication'
            - 'PutBucketTagging'
            - 'DeleteBucketTagging'
            - 'PutBucketWebsite'
            - 'DeleteBucketWebsite'
            - 'PutBucketCors'
            - 'DeleteBucketCors'
            - 'PutBucketPublicAccessBlock'
            - 'DeleteBucketPublicAccessBlock'
            - 'PutBucketAcl'
            - 'PutBucketLogging'
            - 'PutBucketNotification'
            - 'PutBucketVersioning'
            - 'PutBucketObjectLockConfiguration'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsCloudWatchFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-cloudwatch-fwd-rule'
      Description: 'Forwards events from the "logs" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.logs'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'DeleteLogGroup'
            - 'DeleteLogStream'
            - 'AssociateKmsKey'
            - 'DisassociateKmsKey'
            - 'PutRetentionPolicy'
            - 'DeleteRetentionPolicy'
            - 'PutDataProtectionPolicy'
            - 'DeleteDataProtectionPolicy'
            - 'TagResource'
            - 'UntagResource'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsSNSFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-sns-fwd-rule'
      Description: 'Forwards events from the "sns" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.sns'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'DeleteTopic'
            - 'AddPermission'
            - 'RemovePermission'
            - 'SetTopicAttributes'
            - 'Subscribe'
            - 'Unsubscribe'
            - 'TagResource'
            - 'UntagResource'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsOrganizationsFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-organizations-fwd-rule'
      Description: 'Forwards events from the "organizations" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.organizations'
        detail-type:
          - 'AWS API Call via CloudTrail'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsConfigFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-config-fwd-rule'
      Description: 'Forwards events from the "config" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.config'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'DeleteConfigRule'
            - 'PutConfigurationRecorder'
            - 'DeleteConfigurationRecorder'
            - 'StartConfigurationRecorder'
            - 'StopConfigurationRecorder'
            - 'PutDeliveryChannel'
            - 'DeleteDeliveryChannel'
            - 'PutRetentionConfiguration'
            - 'DeleteRetentionConfiguration'
            - 'PutConfigurationAggregator'
            - 'DeleteConfigurationAggregator'
            - 'DeleteAggregationAuthorization'
            - 'DeleteEvaluationResults'
            - 'DeleteOrganizationConfigRule'
            - 'DeleteConformancePack'
            - 'DeleteOrganizationConformancePack'
            - 'DeleteResourceConfig'
            - 'TagResource'
            - 'UntagResource'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

  rOrgSecAlertsAccessAnalyzerFwdRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'org-sec-alerts-access-analyzer-fwd-rule'
      Description: 'Forwards events from the "access-analyzer" event source to the central event bus'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - 'aws.access-analyzer'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'CreateAnalyzer'
            - 'DeleteAnalyzer'
            - 'CreateArchiveRule'
            - 'UpdateArchiveRule'
            - 'ApplyArchiveRule'
            - 'UpdateFindings'
            - 'StartPolicyGeneration'
            - 'TagResource'
            - 'UntagResource'
      Targets:
        - Id: 'rOrgSecEventBus'
          Arn: !Ref pOrgSecEventBus
          RoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/org-sec-alerts-event-fwd-rule-role'

Outputs:

  oTemplateVersion:
    Description: 'Template version'
    Value: '1.0.11'
